"""Persist EDA-01 findings into /docs/data-dictionary.md and /docs/data-quality-notes.md.

Invoked from notebooks/01-hmda-schema-and-quality.ipynb in a single call. Keeps
markdown-generation plumbing out of the analyst notebook. Idempotent: each run
replaces a delimited block rather than appending.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd

DICT_BEGIN = "<!-- BEGIN:hmda-lar-fields -->"
DICT_END = "<!-- END:hmda-lar-fields -->"


def _splice_block(text: str, begin: str, end: str, new_block: str) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if pattern.search(text):
        return pattern.sub(lambda _m: new_block, text)
    return text.rstrip() + "\n\n" + new_block + "\n"


def _type_mode(s: pd.Series) -> str:
    vals = set(s.tolist())
    if "mixed" in vals:
        return "mixed"
    return s.mode().iat[0]


def _build_dict_block(
    *,
    profile_df: pd.DataFrame,
    presence: pd.DataFrame,
    years: list[int],
    code_field_names: set[str],
    exempt_field_names: set[str],
    run_date: str,
) -> str:
    type_mode_series = profile_df.groupby("column")["inferred"].agg(_type_mode)
    null_mean = profile_df.groupby("column")["null_rate"].mean().round(4)

    field_tbl = pd.DataFrame(
        {
            "present_in_years": presence["present_in_years"],
            "inferred_type": type_mode_series.reindex(presence.index),
            "avg_null_rate_3y": null_mean.reindex(presence.index).fillna(1.0),
        }
    )
    field_tbl = field_tbl.reset_index().rename(columns={"index": "column"})
    field_tbl = field_tbl.sort_values("column").reset_index(drop=True)

    def note_for(col: str) -> str:
        bits = []
        if col in code_field_names:
            bits.append("code-list validated")
        if col in exempt_field_names:
            bits.append("exempt-eligible")
        return "; ".join(bits)

    field_tbl["notes"] = field_tbl["column"].map(note_for)

    rows = [
        "| Column | Years | Inferred type | 3y avg null rate | Notes |",
        "| --- | --- | --- | --- | --- |",
    ]
    for _, r in field_tbl.iterrows():
        rows.append(
            f"| `{r['column']}` | {int(r['present_in_years'])}/{len(years)} | "
            f"{r['inferred_type']} | {r['avg_null_rate_3y']:.2%} | {r['notes']} |"
        )

    return "\n".join(
        [
            DICT_BEGIN,
            f"<!-- generated by notebooks/01-hmda-schema-and-quality.ipynb on {run_date} -->",
            "",
            "### HMDA LAR fields (2022 to 2024)",
            "",
            "Source: CFPB nationwide public LAR (data-browser API). Union of "
            "columns across three vintages. ULI (`universal_loan_identifier`) "
            "is intentionally absent from this release per CFPB disclosure policy.",
            "",
            "\n".join(rows),
            "",
            DICT_END,
        ]
    )


def _build_dq_block(
    *,
    counts_df: pd.DataFrame,
    all_cols: list[str],
    inconsistent: pd.DataFrame,
    mixed_cols: pd.DataFrame,
    dtype_drift_df: pd.DataFrame,
    null_wide_interesting: pd.DataFrame,
    exempt_reporters_df: pd.DataFrame,
    panel_df: pd.DataFrame,
    ri_df: pd.DataFrame,
    orphan_lei_samples: dict[int, list[str]],
    syb_records_by_year: dict[int, int],
    enum_findings: dict[str, Any],
    undoc_count: int,
    run_date: str,
) -> str:
    begin = f"<!-- BEGIN:eda-01-{run_date} -->"
    end = f"<!-- END:eda-01-{run_date} -->"

    row_counts_line = ", ".join(
        f"{int(r['year'])} = {int(r['rows']):,}" for r in counts_df.to_dict("records")
    )
    exempt_line = ", ".join(
        f"{int(r['year'])} = {int(r['distinct_exempt_reporters']):,} LEIs"
        for r in exempt_reporters_df.to_dict("records")
    )
    panel_line = ", ".join(
        f"{int(r['year'])} = {int(r['distinct_leis']):,} LEIs across {int(r['rows']):,} rows"
        for r in panel_df.to_dict("records")
    )

    dtype_lines = ["| Column | 2022 int% | 2024 int% | Delta |", "| --- | --- | --- | --- |"]
    for _, r in dtype_drift_df.iterrows():
        dtype_lines.append(
            f"| `{r['column']}` | {r['int_pct_2022']:.1f} | "
            f"{r['int_pct_2024']:.1f} | +{r['delta']:.1f} pp |"
        )

    null_lines = ["| Column | 2022 null rate | 2023 null rate | 2024 null rate |", "| --- | --- | --- | --- |"]
    for col, row in null_wide_interesting.iterrows():
        null_lines.append(
            f"| `{col}` | {row.get(2022, float('nan')):.2%} | "
            f"{row.get(2023, float('nan')):.2%} | {row.get(2024, float('nan')):.2%} |"
        )

    ri_lines = [
        "| Year | Roster LEIs | LAR LEIs | Orphan in LAR | Orphan in roster |",
        "| --- | --- | --- | --- | --- |",
    ]
    for _, r in ri_df.iterrows():
        ri_lines.append(
            f"| {int(r['year'])} | {int(r['roster_leis']):,} | "
            f"{int(r['lar_leis']):,} | {int(r['orphan_in_lar'])} | "
            f"{int(r['orphan_in_roster'])} |"
        )

    orphan_detail = "; ".join(
        f"{y}: {', '.join(leis) if leis else 'none'}"
        for y, leis in orphan_lei_samples.items()
    )

    syb_line = ", ".join(f"{y} = {n:,}" for y, n in syb_records_by_year.items())

    return "\n".join(
        [
            begin,
            f"## {run_date} | EDA-01 HMDA Schema and Quality (analyst-first revision)",
            "",
            "### Dataset shape",
            f"Row counts: {row_counts_line}. A 28% drop from 2022 to 2023, soft "
            "+5.8% recovery into 2024. This is the post-COVID rate-shock signature "
            "and the macro context every downstream HMDA notebook operates within.",
            "",
            f"Schema: {len(all_cols)} columns across all three years. Columns absent "
            f"from any year: {len(inconsistent)}. The 2018 HMDA schema is stable "
            "across this window.",
            "",
            "### Data type drift (reporting practice, not schema change)",
            "Several pricing fields show lenders shifting from decimal-formatted "
            "reporting to integer-formatted reporting over the three vintages. "
            "Downstream models must cast these consistently or year-over-year "
            "comparability silently degrades.",
            "",
            "\n".join(dtype_lines),
            "",
            f"Mixed-type columns flagged in at least one year: "
            f"{mixed_cols['column'].nunique()}. Most of these are mixed by design "
            "(HMDA uses `Exempt`, `NA`, `1111`/`8888`/`9999` sentinels for "
            "not-applicable values). The drift table above isolates the subset "
            "where lender reporting practice changed year over year.",
            "",
            "### Non-structural null fields worth watching",
            "",
            "\n".join(null_lines),
            "",
            "Structural multi-slot fields (applicant_race-5, aus-5, etc) "
            "exceeding 99% null are expected and excluded from this list.",
            "",
            "### Partial-exemption panel",
            f"Distinct reporters using at least one `Exempt` value per year: "
            f"{exempt_line}. The 2022 to 2023 jump (+47%) is a structural "
            "shift in how many small reporters exercise partial exemption, "
            "likely driven by the rate-shock volume collapse dropping more "
            "lenders below the full-reporting threshold. Any pricing analysis "
            "downstream must segment full vs partial reporters.",
            "",
            "### Reporter grain and panel churn",
            f"ULI absent in all three vintages. Panel: {panel_line}. "
            "2023 added 649 LEIs despite 28% less origination volume than "
            "2022, meaning smaller average books per lender. Refi specialists "
            "exited, niche/portfolio lenders persisted or entered. Decision: "
            "downstream loan-grain models cannot rely on a natural PK from the "
            "nationwide LAR. Use a synthetic row-ordinal key or switch source "
            "to the LAR release that preserves ULI.",
            "",
            "### Filer-roster alignment",
            "",
            "\n".join(ri_lines),
            "",
            f"Orphan-in-LAR LEIs (filed without registration) by year: "
            f"{orphan_detail}. These will join-null to any lender attribute "
            "(asset size, charter type) downstream unless handled explicitly.",
            "",
            f"SYB (LEI 4LJGQ9KJ9S0CP4B1FY29) records per year: {syb_line}. "
            "SYB volume dropped roughly 13% across the window vs the national "
            "24% drop. The anchor case held up better than the market.",
            "",
            "### Enum distributions and anomalies",
            f"Undocumented enum values found across 9 code-encoded fields: "
            f"{undoc_count}. Observed distribution shifts worth carrying forward: "
            f"{enum_findings.get('narrative', 'see notebook section 8')}.",
            "",
            end,
        ]
    )


def persist_findings(
    *,
    profile_df: pd.DataFrame,
    counts_df: pd.DataFrame,
    presence: pd.DataFrame,
    all_cols: list[str],
    inconsistent: pd.DataFrame,
    mixed_cols: pd.DataFrame,
    dtype_drift_df: pd.DataFrame,
    null_wide_interesting: pd.DataFrame,
    exempt_reporters_df: pd.DataFrame,
    panel_df: pd.DataFrame,
    ri_df: pd.DataFrame,
    orphan_lei_samples: dict[int, list[str]],
    syb_records_by_year: dict[int, int],
    enum_findings: dict[str, Any],
    undoc_count: int,
    code_field_names: set[str],
    exempt_field_names: set[str],
    years: list[int],
    repo_root: Path,
) -> tuple[Path, Path]:
    """Write dictionary + DQ notes sections. Returns the two paths written."""
    run_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    dict_path = repo_root / "docs" / "data-dictionary.md"
    dq_path = repo_root / "docs" / "data-quality-notes.md"

    dict_block = _build_dict_block(
        profile_df=profile_df,
        presence=presence,
        years=years,
        code_field_names=code_field_names,
        exempt_field_names=exempt_field_names,
        run_date=run_date,
    )
    dq_block = _build_dq_block(
        counts_df=counts_df,
        all_cols=all_cols,
        inconsistent=inconsistent,
        mixed_cols=mixed_cols,
        dtype_drift_df=dtype_drift_df,
        null_wide_interesting=null_wide_interesting,
        exempt_reporters_df=exempt_reporters_df,
        panel_df=panel_df,
        ri_df=ri_df,
        orphan_lei_samples=orphan_lei_samples,
        syb_records_by_year=syb_records_by_year,
        enum_findings=enum_findings,
        undoc_count=undoc_count,
        run_date=run_date,
    )

    dict_text = dict_path.read_text() if dict_path.exists() else "# Data Dictionary\n"
    dict_path.write_text(_splice_block(dict_text, DICT_BEGIN, DICT_END, dict_block))

    dq_begin = f"<!-- BEGIN:eda-01-{run_date} -->"
    dq_end = f"<!-- END:eda-01-{run_date} -->"
    dq_text = dq_path.read_text() if dq_path.exists() else "# Data Quality Notes\n"
    dq_path.write_text(_splice_block(dq_text, dq_begin, dq_end, dq_block))

    return dict_path, dq_path
